
### Send POST createReview - 리뷰 생성
POST http://localhost:8080/reviews
Content-Type: application/json

{
  "reservationId" : 13
  ,"starRate" : 4.5
  ,"title" : "최고의 맛"
  ,"comment" : "좋습니다"
}

### GET searchReviews 상점id로 리뷰 조회
GET http://localhost:8080/reviews?storeId=3
Accept: application/json

